apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfl-stats-ui
  namespace: nflstats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfl-stats-ui
  template:
    metadata:
      labels:
        app: nfl-stats-ui
    spec:
      containers:
        - name: nfl-stats-ui
          image: 192.168.1.113:5000/nfl-stats-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nfl-stats-ui
  namespace: nflstats
spec:
  type: NodePort
  selector:
    app: nfl-stats-ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
